In [1]:
def multiply(a, b):
    return a * b

print(multiply(3, 4))  # Output: 12

12


## Find BMI

In [9]:
weight = float(input("Enter your weight in kg: "))
height = float(input("Enter your height in meters: "))

def calculate_bmi(weight, height):
    bmi = weight / (height ** 2)
    print("Your BMI is:", bmi)

    if bmi < 18.5:
        category = "underweight"
    elif 18.5 <= bmi < 24.9:
        category = "normal"
    elif 25 <= bmi < 29.9:
        category = "overweight"
    else:
        category = "obese"

    return bmi, category

print(calculate_bmi(weight, height))

Your BMI is: 24.489795918367346
(24.489795918367346, 'normal')


In [10]:
def student(name, age):
    print("Student Name:", name)
    print("Student Age:", age)

student("John Doe", 20)

Student Name: John Doe
Student Age: 20


In [13]:
def greet(name="Guest"):
    print("Hello,", name)

greet("Alice")
greet()

Hello, Alice
Hello, Guest


In [17]:
def function(a, b, c):
    print("Values:", a, b, c)

function(1, 2, 3)
# Using keyword arguments
function(a=1, b=2, c=3)
function(c=3, a=1, b=2)
function(1, c=3, b=2)  # Mixing positional and keyword arguments

Values: 1 2 3
Values: 1 2 3
Values: 1 2 3
Values: 1 2 3


In [21]:
def my_function(*args):
    if len(args) == 2:
        return args[0] + args[1]
    elif len(args) == 3:
        return args[0] + args[1] + args[2]
    else:
        return "Invalid number of arguments"


print(my_function(5, 10,20))  # Output: 15

35


## Normalize Scores

The `normalize_scores` function accepts any number of scores and an optional `scaling_factor`. Each score is multiplied by the scaling factor. The default factor is `1.0`, so scores remain unchanged when no factor is provided.

In [ ]:
def normalize_scores(*scores, scaling_factor=1.0):
    """Scale any number of scores by the supplied factor."""
    return tuple(score * scaling_factor for score in scores)


print("Default factor:", normalize_scores(10, 20, 30))
print("Half scale:", normalize_scores(10, 20, 30, scaling_factor=0.5))
print("Double scale:", normalize_scores(1.5, 2.5, scaling_factor=2.0))
print("No scores:", normalize_scores(scaling_factor=3.0))

Default factor: (10.0, 20.0, 30.0)
Half scale: (5.0, 10.0, 15.0)
Double scale: (3.0, 5.0)
No scores: ()


### Explanation of the test outputs

- `normalize_scores(10, 20, 30)` uses the default factor `1.0`, so the output is `(10.0, 20.0, 30.0)`.
- With `scaling_factor=0.5`, every score is halved, producing `(5.0, 10.0, 15.0)`.
- With `scaling_factor=2.0`, every score is doubled, producing `(3.0, 5.0)`.
- Calling the function without scores returns an empty tuple because there is nothing to scale.

The `*scores` parameter collects an arbitrary number of positional scores, while `scaling_factor` is keyword-only and defaults to `1.0`.

In [26]:
def my_function(**keywargs):
    print(keywargs.items())
    print(type(keywargs))

my_function(name="Alice", age=30, city="New York")
my_function(name="Bob", country="USA", profession="Engineer")

dict_items([('name', 'Alice'), ('age', 30), ('city', 'New York')])
<class 'dict'>
dict_items([('name', 'Bob'), ('country', 'USA'), ('profession', 'Engineer')])
<class 'dict'>


In [1]:
def my_function(**keywargs):
    for key, value in keywargs.items():
        print(f"{key}: {value}")

my_function(name="Alice", age=30, city="New York")

name: Alice
age: 30
city: New York


In [4]:
def calculate_bill(customer,**items):
    sub_total = sum(items.values())
    if sub_total > 50:
        discount = sub_total * 0.1
    elif sub_total > 100:
        discount = sub_total * 0.2
    else:
        discount = 0
    amount_after_discount = sub_total - discount
    tax = amount_after_discount * 0.07
    print(f"Customer: {customer}")
    print(f"Sub Total: ${sub_total:.2f}")
    print(f"Discount: ${discount:.2f}")
    print(f"Tax: ${tax:.2f}")

    
calculate_bill("John Doe", Burger=5.99, Fries=2.49, Soda=1.50)


Customer: John Doe
Sub Total: $9.98
Discount: $0.00
Tax: $0.70


In [6]:
print(abs(-10))  # Output: 10
print(abs(3.14))  # Output: 3.14

10
3.14


In [7]:
def square(x):
    return x * x

numbers = [1, 2, 3, 4, 5]
squared_numbers = list(map(square, numbers))
print(squared_numbers)  # Output: [1, 4, 9,

[1, 4, 9, 16, 25]


In [8]:
words = ["Hello", "world", "Python", "is", "awesome"]

words_length = list(map(len,words))
words_upper = list(map(str.upper, words))

print("Words:", words)
print("Lengths:", words_length)
print("Uppercase:", words_upper)

Words: ['Hello', 'world', 'Python', 'is', 'awesome']
Lengths: [5, 5, 6, 2, 7]
Uppercase: ['HELLO', 'WORLD', 'PYTHON', 'IS', 'AWESOME']


In [9]:
numbers = [1, -2, 3, -4, 5]

result = list(map(abs, numbers))
print(result)  # Output: [1, 2, 3, 4,

[1, 2, 3, 4, 5]


In [16]:
list1 = [1, 5, 3]
list2 = [4, 2, 6]

max_elements = list(map(max, list1, list2))
print(max_elements)  # Output: [4, 5, 6]

min_elements = list(map(min, list1, list2))
print(min_elements)  # Output: [1, 2, 3]

[4, 5, 6]
[1, 2, 3]


In [17]:
numbers = [1, 2, 3, 4, 5]

result = sum(numbers)
print(result)  # Output: 15

15


In [20]:
x = 10
print(isinstance(x, int))  # Output: True

True


In [21]:
square = lambda x: x * x

print(square(5))  # Output: 25

25


In [3]:
users = [
    {"name": "Alice", "age": 30},
    {"name": "Bob", "age": 25},
    {"name": "Charlie", "age": 35}
]

sorted_users = sorted(users, key=lambda user: user["age"])
print(sorted_users)  # Output: [{'name': 'Bob', 'age': 25}, {'name': 'Alice', 'age': 30}, {'name': 'Charlie', 'age': 35}]

[{'name': 'Bob', 'age': 25}, {'name': 'Alice', 'age': 30}, {'name': 'Charlie', 'age': 35}]


In [4]:
student_name = "Kavindi"
registration_number = "ICT2025"
course_name = "BSc Computer Science"
number_of_subjects = 5
total_marks = 420
maximum_possible_marks = 500

# Calculate average marks
average_marks = total_marks / number_of_subjects

# Calculate percentage
percentage = (total_marks / maximum_possible_marks) * 100

# Display student report
print("Student Report")
print("-" * 40)

print(f"Name             : {student_name}")
print(f"Registration No  : {registration_number}")
print(f"Course           : {course_name}")
print(f"Subjects         : {number_of_subjects}")
print(f"Total Marks      : {total_marks}")
print(f"Percentage       : {percentage:.2f}%")
print(f"Average Marks    : {average_marks:.2f}")

Student Report
----------------------------------------
Name             : Kavindi
Registration No  : ICT2025
Course           : BSc Computer Science
Subjects         : 5
Total Marks      : 420
Percentage       : 84.00%
Average Marks    : 84.00
